services:
  - type: web
    name: swapsquad-backend
    env: docker
    rootDirectory: backEnd  # This sets the build context to the backEnd directory
    buildCommand: docker build -t swapsquad-backend .
    dockerfilePath: Dockerfile  # Relative to rootDirectory
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DB_HOST
        fromDatabase:
          name: swapsquad-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: swapsquad-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: swapsquad-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: swapsquad-db
          property: password
      - key: DB_PORT
        value: 5432
      - key: ENVIRONMENT
        value: production
      - key: LOGGING_ENABLED
        value: True
      - key: FRONTEND_URL
        value: https://swapsquad-frontend.onrender.com
      - key: PROJECT_ID
        sync: false
      - key: SECRET
        sync: false
      - key: ENVIRONMENT
        value: live
      - key: SERVER_URL
        value: 0.0.0.0

  - type: web
    name: swapsquad-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.9.1
      - key: BACKEND_URL
        value: https://swapsquad-backend.onrender.com
      - key: STYTCH_PUBLIC_TOKEN
        sync: false

databases:
  - name: swapsquad-db
    databaseName: backend
    user: backend
    plan: free