"""adds comment support

Revision ID: ac83a268b570
Revises: 9bb30ac3302f
Create Date: 2024-07-15 22:14:57.975887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ac83a268b570'
down_revision: Union[str, None] = '9bb30ac3302f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('positive_comments', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
    op.add_column('solutions', sa.Column('negative_comments', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'negative_comments')
    op.drop_column('solutions', 'positive_comments')
    # ### end Alembic commands ###
