from enum import Enum

class ItemCategory(str, Enum):
    TEXTBOOKS = "TEXTBOOKS"
    ELECTRONICS = "ELECTRONICS"
    FURNITURE = "FURNITURE"
    CLOTHING = "CLOTHING"
    SCHOOL_SUPPLIES = "SCHOOL_SUPPLIES"
    SPORTS_EQUIPMENT = "SPORTS_EQUIPMENT"
    MUSICAL_INSTRUMENTS = "MUSICAL_INSTRUMENTS"
    OTHER = "OTHER"

class ItemStatus(str, Enum):
    STATUS_NEW = "STATUS_NEW"
    STATUS_INTERESTED = "STATUS_INTERESTED"
    STATUS_NEGOTIATIONS = "STATUS_NEGOTIATIONS"
    STATUS_CLOSED = "STATUS_CLOSED"

class ItemCondition(str, Enum):
    CONDITION_NEW = "CONDITION_NEW"
    CONDITION_USED = "CONDITION_USED"