from enum import Enum

class ItemCategory(str, Enum):
    TEXTBOOKS = "TEXTBOOKS"
    ELECTRONICS = "ELECTRONICS"
    FURNITURE = "FURNITURE"
    CLOTHING = "CLOTHING"
    SCHOOL_SUPPLIES = "SCHOOL_SUPPLIES"
    SPORTS_EQUIPMENT = "SPORTS_EQUIPMENT"
    MUSICAL_INSTRUMENTS = "MUSICAL_INSTRUMENTS"
    OTHER = "OTHER"