"""Added Chat Product Inquiry Table

Revision ID: 28f89a8b6e9d
Revises: 85e786a96b1d
Create Date: 2024-11-05 20:17:08.834666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f89a8b6e9d'
down_revision: Union[str, None] = '85e786a96b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###'
    chatmessagetype_enum = sa.Enum('TEXT', 'PRODUCT_INQUIRY', name='chatmessagetype')
    chatmessagetype_enum.create(op.get_bind(), checkfirst=True)

    # Create the chat product inquiry table
    op.create_table('chat_product_inquiry',
    sa.Column('chat_message_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_product_inquiry_id'), 'chat_product_inquiry', ['id'], unique=False)
    op.add_column('chat_messages', sa.Column('type', chatmessagetype_enum, server_default='TEXT', nullable=False))
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'type')
    op.drop_index(op.f('ix_chat_product_inquiry_id'), table_name='chat_product_inquiry')
    op.drop_table('chat_product_inquiry')

    # Drop the enum type
    chatmessagetype_enum = sa.Enum('TEXT', 'PRODUCT_INQUIRY', name='chatmessagetype')
    chatmessagetype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
