"""add_items_fields

Revision ID: 426191c2d92e
Revises: e231539a90d0
Create Date: 2024-10-28 19:41:56.202998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426191c2d92e'
down_revision: Union[str, None] = 'e231539a90d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interested_buyers',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'user_id')
    )
    op.add_column('items', sa.Column('name', sa.String(), nullable=False))
    op.add_column('items', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('items', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('items', 'address')
    op.drop_column('items', 'longitude')
    op.drop_column('items', 'latitude')
    op.drop_column('items', 'name')
    op.drop_table('interested_buyers')
    # ### end Alembic commands ###
