"""Add item_images column

Revision ID: 94a00170590a
Revises: 426191c2d92e
Create Date: 2024-10-29 00:38:38.142013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a00170590a'
down_revision: Union[str, None] = '426191c2d92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('images', sa.String(), nullable=False))
    op.drop_column('items', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('items', 'images')
    # ### end Alembic commands ###
