"""Add seller profiles table

Revision ID: c5ca260c0a75
Revises: 335e3accb204
Create Date: 2024-10-25 08:01:26.342192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ca260c0a75'
down_revision: Union[str, None] = '335e3accb204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_profiles',
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('seller_id', 'id')
    )
    op.create_index(op.f('ix_seller_profiles_id'), 'seller_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_profiles_id'), table_name='seller_profiles')
    op.drop_table('seller_profiles')
    # ### end Alembic commands ###
