"""Added deleted_at col for interested_buyers

Revision ID: d8843cc61c37
Revises: 78d4fe49bd79
Create Date: 2024-10-29 02:59:06.352764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8843cc61c37'
down_revision: Union[str, None] = '78d4fe49bd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interested_buyers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interested_buyers', 'deleted_at')
    # ### end Alembic commands ###
