"""Added Product Embeddings Table

Revision ID: def39723a077
Revises: 28f89a8b6e9d
Create Date: 2024-11-06 01:16:18.771834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def39723a077'
down_revision: Union[str, None] = '28f89a8b6e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name_embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('category_embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('address_embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('price_embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('description_embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('condition_embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_embeddings')
    # ### end Alembic commands ###
