import os
from dotenv import load_dotenv
from sqlalchemy import URL, create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import Session as SQLAlchemySession
from alembic.config import Config
from alembic import command
from backend.config import settings

# Load environment variables
load_dotenv()

# Set default values
DB_PORT = os.getenv("DB_PORT", "5432")
DB_USER = os.getenv("DB_USER", "backend")
DB_PASSWORD = os.getenv("DB_PASSWORD", "secret")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_NAME = os.getenv("DB_NAME", "backend")

url_object = URL.create(
    "postgresql+psycopg2",
    username=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=int(DB_PORT),
    database=DB_NAME,
)

# Create database engine
engine = create_engine(url_object)

# Create sessionmaker
Session = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def init_db():
    alembic_cfg = Config(
        os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "alembic.ini")
    )
    # command.revision(alembic_cfg, autogenerate=True, message="Autogenerated changes")
    command.upgrade(alembic_cfg, "head")

def get_db() -> SQLAlchemySession:
    """
    Get a database session.
    Yields a SQLAlchemy Session that will be closed after use.
    """
    db = Session()
    try:
        yield db
    finally:
        db.close()