import os
from sqlalchemy import URL, create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import Session as SQLAlchemySession
from alembic.config import Config
from alembic import command
from backend.config import settings
from dotenv import load_dotenv

from backend.db_models.base import BaseDbModel

# Load environment variables from .env file
load_dotenv()

url_object = URL.create(
    "postgresql+psycopg2",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT")),
    database=os.getenv("DB_NAME"),
)

# Create database engine
engine = create_engine(settings.DATABASE_URL)

# Create sessionmaker
Session = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def init_db():
    alembic_cfg = Config(
        os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "alembic.ini")
    )
    # command.revision(alembic_cfg, autogenerate=True, message="Autogenerated changes")
    command.upgrade(alembic_cfg, "head")

def get_db() -> SQLAlchemySession:
    """
    Get a database session.
    Yields a SQLAlchemy Session that will be closed after use.
    """
    db = Session()
    try:
        yield db
    finally:
        db.close()