import os
from sqlalchemy import URL, create_engine
from sqlalchemy.orm import sessionmaker
from alembic.config import Config
from alembic import command

from backend.db_models.base import BaseDbModel

url_object = URL.create(
    "postgresql+psycopg2",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT")),
    database=os.getenv("DB_NAME"),
)
engine = create_engine(url_object, echo=False)
Session = sessionmaker(engine)


def init_db():
    alembic_cfg = Config(
        os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "alembic.ini")
    )
    # command.revision(alembic_cfg, autogenerate=True, message="Autogenerated changes")
    command.upgrade(alembic_cfg, "head")
