server {

  listen  443 ssl;
  ssl_certificate         /tls/server.crt.pem;
  ssl_certificate_key     /tls/server.key.pem;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;

  }

  error_page   500 502 503 504  /50x.html;

  location /health {
    add_header Content-Type text/plain;
    return 200 'OK';
  }
}
